### ISSUE TITLE
Begin to  translate Readme.md!

### ISSUE THREAD

**Issue by wsdjeg** [Neovim-cn/vim-galore#1]
@mhinz
I was beginning to translate the Readme.md,and the file name is `Readme_zh_CN.md`.

https://github.com/Neovim-cn/Neovim-cn.gitgub.io/issues/1

**Comment by mhinz** [comment]
Okay, great! But keep in mind that vim-galore is mostly about Vim at the moment.

**Comment by wsdjeg** [comment]
I know,thanks

**Comment by wsdjeg** [comment]
@icecity96 
感谢开始翻译这个项目,由于这个项目目前一直在更新中,所以我们需要遵守一定的规则使得本仓库能够正常合并上游仓库. 除了修改`*.zh_cn`这个文件以外,其他文件不需要修改. 如果上游修改了,请及时更新
